name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build & Push Image
        run: |
          echo ${{ secrets.DOCKERTOKEN }} | docker login -u "YOUR-DOCKERHUB-USERNAME" --password-stdin
          docker build -t YOUR-DOCKERHUB-USERNAME/fastapi-demo:latest .
          docker push YOUR-DOCKERHUB-USERNAME/fastapi-demo:latest